//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDRENTAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        public int copy_id { get; set; }
        public int client_id { get; set; }
        public Nullable<System.DateTimeOffset> date_of_rental { get; set; }
        public Nullable<System.DateTimeOffset> date_of_return { get; set; }
    
        public virtual client client { get; set; }
        public virtual copy copy { get; set; }
    }
}
